language: php

php:
    - "5.6"
    - "7.1"
    - "7.2"

git:
  depth: 10

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
    - composer install --prefer-dist --no-interaction --no-scripts

script:
    - ./vendor/bin/php-cs-fixer --dry-run -v fix . --rules=@PSR2
